import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';import worker from '../.generated/worker.mjs';
const origin='https://portfolio.test',email='owner@example.com';
function environment(){
 const db=new DatabaseSync(':memory:');
 db.exec('CREATE TABLE site_content(id TEXT PRIMARY KEY,payload TEXT,version INTEGER); CREATE TABLE projects(id TEXT PRIMARY KEY,payload TEXT,version INTEGER,position INTEGER); CREATE TABLE uploads(id TEXT PRIMARY KEY,owner TEXT,mime TEXT,size INTEGER,created_at TEXT,blob_url TEXT);');
 const files=new Map();
 return {
  EDITOR_EMAIL:email,currentUser:email,
  DB:{prepare(sql){return {
   args:[],bind(...args){this.args=args;return this},
   async all(){return {results:db.prepare(sql).all(...this.args)}},
   async run(){const r=db.prepare(sql).run(...this.args);return {meta:{changes:Number(r.changes)}}}
  }}},
  BUCKET:{async put(id,data,options){files.set(id,{data,options});return {url:"https://blob.example.com/"+id}},async delete(id){files.delete(id)},async get(id){const f=files.get(id);return f?{body:f.data,writeHttpMetadata(h){h.set('content-type',f.options.httpMetadata.contentType)}}:null}},
  ASSETS:{async fetch(){return new Response('asset')}}
 };
}
function req(path,method='GET',payload,identity=email,extra={}){const headers={...extra};if(identity){headers['oai-authenticated-user-id']='site-user-'+identity;headers['oai-authenticated-user-email']=identity}if(method!=='GET'){headers.origin=origin;headers['x-editor-request']='1';headers['content-type']='application/json'}return new Request(origin+path,{method,headers,body:payload===undefined?undefined:JSON.stringify(payload)})}
test('existing project saves persist, render safely, and reject stale edits',async()=>{const env=environment();const initial=await (await worker.fetch(req('/api/editor/projects'),env)).json();assert.equal(initial.projects.length,9);const p={...initial.projects[0],title:'Updated <script>alert(1)</script>',github:'https://github.com/MIRSAHINALI/test',demo:'https://example.com'};const response=await worker.fetch(req('/api/editor/projects/'+p.id,'PUT',p),env);assert.equal(response.status,200);assert.equal((await response.json()).project.version,1);const publicData=await (await worker.fetch(req('/projects-data.json','GET',undefined,null),env)).json();assert.equal(publicData[0].title,p.title);assert.equal(publicData[0].github,p.github);const html=await (await worker.fetch(req('/projects/'),env)).text();assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>alert(1)</script>'));assert.ok(html.includes('project-hospital.png'));assert.equal((await worker.fetch(req('/api/editor/projects/'+p.id,'PUT',p),env)).status,409)});
test('new project is durable and joins portfolio; unsafe URLs and CSRF rejected',async()=>{const env=environment();const p={title:'New project',description:'Description',category:'Web',stack:['React'],image:'https://example.com/image.png',github:'',demo:''};const response=await worker.fetch(req('/api/editor/projects','POST',p),env);assert.equal(response.status,201);const created=(await response.json()).project;assert.ok(created.id);assert.equal((await (await worker.fetch(req('/projects-data.json'),env)).json()).length,10);const bad={...p,demo:'javascript:alert(1)'};assert.equal((await worker.fetch(req('/api/editor/projects','POST',bad),env)).status,400);const csrf=req('/api/editor/projects','POST',p);csrf.headers.set('origin','https://evil.test');assert.equal((await worker.fetch(csrf,env)).status,403)});
test('uploads validate file content and can be retrieved after upload',async()=>{const env=environment();const headers={'oai-authenticated-user-id':'owner-id','oai-authenticated-user-email':email,origin,'x-editor-request':'1'};const bytes=fs.readFileSync('public/assets/project-weather.png');const response=await worker.fetch(new Request(origin+'/api/editor/upload',{method:'POST',headers,body:bytes}),env);assert.equal(response.status,201);const {url}=await response.json();const image=await worker.fetch(req(url,'GET',undefined,null),env);assert.equal(image.status,302);assert.match(image.headers.get('location'),/^https:\/\/blob.example.com\//);assert.equal((await worker.fetch(new Request(origin+'/api/editor/upload',{method:'POST',headers,body:'<svg onload="alert(1)">'}),env)).status,400);assert.equal((await worker.fetch(new Request(origin+'/api/editor/upload',{method:'POST',headers,body:new Uint8Array(5*1024*1024+1)}),env)).status,400)});
test('storage failures are recoverable and never report success',async()=>{const env=environment();env.DB.prepare=()=>{throw new Error('Database unavailable')};const response=await worker.fetch(req('/api/editor/projects'),env);assert.equal(response.status,503);assert.match((await response.json()).error,/temporarily unavailable/)});
test('home content persists with safe markup, ordering, and optimistic conflicts',async()=>{const env=environment();const initial=await (await worker.fetch(req('/api/editor/content'),env)).json();assert.equal(initial.version,0);assert.equal(initial.content.skills.length,19);const c=initial.content;c.profile.name='<script>name</script>';c.profile.summary='New summary';c.experience.reverse();c.certifications.push({name:'New certification',issuer:'Test',url:'https://example.com/cert'});c.education.push({degree:'New degree',institution:'Test',dates:'2027',score:'A',image:''});c.photos.push({image:'/assets/project-weather.png',caption:'<b>Photo</b>'});const save=await worker.fetch(req('/api/editor/content','PUT',{content:c,version:0}),env);assert.equal(save.status,200);assert.equal((await save.json()).version,1);assert.equal((await worker.fetch(req('/api/editor/content','PUT',{content:c,version:0}),env)).status,409);const home=await (await worker.fetch(req('/'),env)).text();assert.ok(home.includes('New summary'));assert.ok(home.includes('New certification'));assert.ok(home.includes('New degree'));assert.ok(!home.includes('<script>name'));assert.ok(home.indexOf('May 2025')<home.indexOf('June 2026'));assert.ok(!home.includes('<!--CONTENT:'));assert.ok(home.includes('href="/resume"'));const gallery=await (await worker.fetch(req('/gallery/'),env)).text();assert.ok(gallery.includes('&lt;b&gt;Photo&lt;/b&gt;'));const unsafe=structuredClone(c);unsafe.profile.photo='javascript:alert(1)';assert.equal((await worker.fetch(req('/api/editor/content','PUT',{content:unsafe,version:1}),env)).status,400);const csrf=req('/api/editor/content','PUT',{content:c,version:1});csrf.headers.set('origin','https://evil.test');assert.equal((await worker.fetch(csrf,env)).status,403);assert.equal((await worker.fetch(req('/api/editor/content'),{...env,currentUser:null})).status,401);});
test('PDF résumé uploads require a PDF signature and publish through a stable redirect',async()=>{const env=environment();const headers={origin,'x-editor-request':'1'};const initial=await (await worker.fetch(req('/api/editor/content'),env)).json();const upload=body=>worker.fetch(new Request(origin+'/api/editor/resume',{method:'POST',headers,body}),env);assert.equal((await upload('<html>not a PDF</html>')).status,400);assert.equal((await upload(new Uint8Array(3*1024*1024+1))).status,400);const r=await upload('%PDF-1.7\n%test');assert.equal(r.status,201);const {url}=await r.json();initial.content.resume.url=url;assert.equal((await worker.fetch(req('/api/editor/content','PUT',{content:initial.content,version:0}),env)).status,200);const redirect=await worker.fetch(req('/resume'),env);assert.equal(redirect.status,302);assert.equal(redirect.headers.get('location'),url);assert.equal(redirect.headers.get('cache-control'),'no-store');assert.equal((await worker.fetch(req(url),env)).status,302);for(const path of ['/','/gallery/','/projects/'])assert.ok((await (await worker.fetch(req(path),env)).text()).includes('href="/resume"'));});
