export const schema = [
 {key:'profile',label:'Home & profile',fields:[['name','Name'],['headline','Role / headline'],['intro','Introduction'],['summary','Self-summary','textarea'],['photo','Profile photo','image'],['email','Contact email','email'],['brand','Navbar name'],['footer','Footer text']]},
 {key:'experience',label:'Experience',list:true,fields:[['company','Company'],['role','Role'],['date','Dates'],['image','Company logo','image'],['details','Bullet points (one per line)','textarea']]},
 {key:'education',label:'Education',list:true,fields:[['degree','Degree'],['institution','Institution'],['dates','Dates'],['score','Grade / CGPA'],['image','Institution logo','image']]},
 {key:'skills',label:'Skills',list:true,fields:[['name','Skill'],['image','Logo','image'],['symbol','Text symbol (if no logo)']]},
 {key:'certifications',label:'Certifications',list:true,fields:[['name','Certificate'],['issuer','Issuer / date'],['url','Certificate link','url']]},
 {key:'socials',label:'Socials',list:true,fields:[['name','Platform'],['url','Profile link (HTTPS or mailto)','social'],['image','Icon','image']]},
 {key:'coding',label:'Coding profiles',list:true,fields:[['name','Platform'],['url','Profile link','url'],['handle','Handle'],['description','Profile summary','textarea']]},
 {key:'resume',label:'Résumé',fields:[['url','Résumé PDF','pdf']]},
 {key:'gallery',label:'Gallery',fields:[['title','Heading'],['subtitle','Subtitle'],['description','Description','textarea'],['video','Background video URL (MP4 / WebM)','media']]},
 {key:'photos',label:'Gallery photos',list:true,fields:[['image','Photo','image'],['caption','Caption']]}
];
export class ContentError extends Error{}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function validLink(s,kind){if(!s)return s;if(['image','pdf','media'].includes(kind)&&/^\/(assets|uploads)\/[\w.-]+$/.test(s))return s;if(kind==='social'&&/^mailto:[^\s<>@]+@[^\s<>@]+$/.test(s))return s;try{const u=new URL(s);if(u.protocol==='https:'&&!u.username&&!u.password)return u.href}catch{}throw new ContentError('Links must use HTTPS. Uploaded files and existing /assets/ paths are also accepted.');}
export function validateContent(data){if(!data||typeof data!=='object'||Array.isArray(data))throw new ContentError('Invalid content.');const out={};for(const section of schema){const validate=item=>{if(!item||typeof item!=='object'||Array.isArray(item))throw new ContentError('Invalid entry.');const result={};for(const [key,label,kind] of section.fields){const v=item[key];if(typeof v!=='string'||v.length>(kind==='textarea'?6000:2048))throw new ContentError(`${label} is missing or too long.`);result[key]=['url','social','image','pdf','media'].includes(kind)?validLink(v.trim(),kind):v.trim();if(kind==='email'&&!/^[^\s<>@]+@[^\s<>@]+\.[^\s<>@]+$/.test(result[key]))throw new ContentError('Enter a valid contact email.');}return result;};if(section.list){if(!Array.isArray(data[section.key])||data[section.key].length>50)throw new ContentError('Use at most 50 entries per section.');out[section.key]=data[section.key].map(validate);}else out[section.key]=validate(data[section.key]);}if(!out.profile.name||!out.profile.brand)throw new ContentError('Name and navbar name are required.');return out;}
export async function getContent(env,defaults){const r=await env.DB.prepare("SELECT payload,version FROM site_content WHERE id='main'").all();return r.results[0]?{content:JSON.parse(r.results[0].payload),version:r.results[0].version}:{content:defaults,version:0};}
const img=(url,alt,attrs='')=>url?`<img src="${esc(url)}" alt="${esc(alt)}" ${attrs}>`:'';
export function renderContent(template,c){const p=c.profile;const slots={
 portrait:img(p.photo,p.name,'class="portrait" width="220" height="200"'),name:esc(p.name).replace(' ','<br>'),headline:esc(p.headline),intro:esc(p.intro),summary:esc(p.summary),
 skills:c.skills.map(x=>`<span class="skill" title="${esc(x.name)}" aria-label="${esc(x.name)}">${x.image?img(x.image,x.name,'width="56" height="56"'):`<span class="skill-label">${esc(x.symbol||x.name)}</span>`}</span>`).join(''),
 experience:c.experience.map(x=>`<article class="exp-item"><div class="avatar company-logo">${img(x.image,x.company,'width="60" height="60"')}</div><div><div class="exp-top"><h3>${esc(x.company)}</h3><span class="exp-date">${esc(x.date)}</span></div><p class="exp-role">${esc(x.role)}</p><ul>${x.details.split('\n').filter(Boolean).map(t=>`<li>${esc(t)}</li>`).join('')}</ul></div></article>`).join(''),
 education:c.education.map(x=>`<div class="degree">${img(x.image,x.institution,'width="44" height="50"')}<div><h3>${esc(x.degree)}</h3><p>${esc(x.institution)} · ${esc(x.dates)}</p><p>${esc(x.score)}</p></div></div>`).join(''),
 certifications:c.certifications.map(x=>`<li><span class="cert-mark" aria-hidden="true">✧</span><div><div class="cert-name">${x.url?`<a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.name)}</a>`:esc(x.name)}</div><div class="cert-issuer">${esc(x.issuer)}</div></div></li>`).join(''),
 socials:c.socials.map(x=>`<a href="${esc(x.url)}" aria-label="${esc(x.name)}" title="${esc(x.name)}" target="_blank" rel="noopener">${x.image?img(x.image,'','width="44" height="44"'):esc(x.name)}</a>`).join(''),
 coding:c.coding.map(x=>`<article class="card stats-card"><div class="stat-head"><h2>${esc(x.name)}</h2><a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.handle)}</a></div><p>${esc(x.description)}</p><a class="profile-action" href="${esc(x.url)}" target="_blank" rel="noopener">View profile ↗</a></article>`).join(''),
 'gallery-title':esc(c.gallery.title),'gallery-subtitle':esc(c.gallery.subtitle),'gallery-description':esc(c.gallery.description),'gallery-video':c.gallery.video?`<source src="${esc(c.gallery.video)}">`:'',photos:`<section class="managed-gallery">${c.photos.map(x=>`<figure>${img(x.image,x.caption,'loading="lazy"')}<figcaption>${esc(x.caption)}</figcaption></figure>`).join('')}</section>`
};return template.replace('<head>','<head><meta name="portfolio-contact" content="'+esc(p.email)+'">').replaceAll('/assets/Mir-Sahin-Ali-Resume.pdf','/resume').replaceAll('mailto:mir1sahin123@gmail.com',()=> 'mailto:'+esc(p.email)).replace(/(<a class="brand" href="\/">)Sahin/g,(_,prefix)=>prefix+esc(p.brand)).replaceAll('Designed and developed for Mir Sahin Ali',()=>esc(p.footer)).replaceAll(' | Mir Sahin Ali</title>',()=> ' | '+esc(p.name)+'</title>').replace(/<!--CONTENT:([\w-]+)-->/g,(_,key)=>slots[key]??'');}
